/*
 * The server environment a browser build targets (CLAUDE.md §8e), from `-Pwyr.env=dev`: local, dev or
 * prod, local when absent. A page has nothing of its own to read at start, so the name is written into
 * a Kotlin constant, `internal const val WYR_ENV`, which the page's entry point parses.
 *
 * Applied by each module with a browser entry point, the game's `:app:webApp` and the moderation app
 * `:app:adminApp`, after it sets `extra["wyrEnvPackage"]` to the package the constant goes in:
 *
 *     extra["wyrEnvPackage"] = "io.ntole.wyr"
 *     apply(from = rootProject.file("gradle/wyr-env.gradle.kts"))
 *
 * It registers `generateWyrEnv`, whose output directory the module adds to its `webMain` sources. A
 * script rather than a plugin: it is one task, and a convention plugin would need an included build of
 * its own.
 *
 * Checked here as `WyrEnvironment.parse` would, so a name it does not know fails the build rather than
 * every page load.
 */
tasks.register("generateWyrEnv") {
    // Read here, into locals, so the task action captures only these and not the script.
    val packageName = project.extra["wyrEnvPackage"] as String
    val requested = providers.gradleProperty("wyr.env").orElse("")
    val outputDir = layout.buildDirectory.dir("generated/wyrEnv/kotlin")
    inputs.property("package", packageName)
    inputs.property("environment", requested)
    outputs.dir(outputDir)

    doLast {
        val name =
            requested
                .get()
                .trim()
                .lowercase()
                .ifEmpty { "local" }
        require(name in setOf("local", "dev", "prod")) {
            "wyr.env must be local, dev or prod, but is \"${requested.get()}\""
        }
        // Emptied first, so a constant written into another package before cannot linger beside it.
        outputDir.get().asFile.deleteRecursively()
        val file = outputDir.get().file("${packageName.replace('.', '/')}/WyrEnv.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package $packageName
            |
            |// Generated by generateWyrEnv (gradle/wyr-env.gradle.kts) from -Pwyr.env. Do not edit.
            |internal const val WYR_ENV: String = "$name"
            |
            """.trimMargin(),
        )
    }
}
