/*
 * The PostHog project a game build sends its analytics to (CLAUDE.md §8g): its key, and its host, the
 * EU cloud when none is named. Each is the Gradle property `wyr.posthog.key` or `wyr.posthog.host`
 * (`-Pwyr.posthog.key=...`, or `~/.gradle/gradle.properties`), or else the same name in the
 * repository's `local.properties`, which git ignores. No key is analytics off, which is how every test
 * and every CI build runs; a key is never committed.
 *
 * Applied by each game module that builds an app from them, which reads what it needs:
 *
 * - `:app:androidApp` reads `extra["wyrPosthogKey"]` and `extra["wyrPosthogHost"]` into its
 *   BuildConfig, one key for every flavor (events name their environment).
 * - `:app:webApp` sets `extra["wyrAnalyticsPackage"]` first, and applies gradle/wyr-version.gradle.kts,
 *   which sets `extra["wyrAppVersion"]` and `extra["wyrBuildNumber"]`; this registers
 *   `generateWyrAnalytics`, which writes the two settings, with the version and the build number,
 *   into Kotlin constants in that package, `POSTHOG_KEY`, `POSTHOG_HOST`, `APP_VERSION` and
 *   `BUILD_NUMBER`, whose output directory the module adds to its `webMain` sources, as
 *   `generateWyrEnv` does the environment (gradle/wyr-env.gradle.kts). The build number is no
 *   analytics setting, but it is the version's, which is written here already.
 *
 * Desktop and iOS name theirs as they name the environment, when the app starts: the `WYR_POSTHOG_KEY`
 * and `WYR_POSTHOG_HOST` variables, and the same build settings in the Xcode project's
 * `Local.xcconfig`. A key holding anything but letters, digits, `_` and `-`, or a host holding a quote,
 * a backslash, a `$` or a space, fails the build here, since each is written into generated code.
 */
import java.io.StringReader
import java.util.Properties

val localProperties =
    Properties().apply {
        providers
            .fileContents(rootProject.layout.projectDirectory.file("local.properties"))
            .asText
            .orNull
            ?.let { text -> load(StringReader(text)) }
    }

fun analyticsSetting(name: String): String =
    (providers.gradleProperty(name).orNull ?: localProperties.getProperty(name)).orEmpty().trim()

val posthogKey = analyticsSetting("wyr.posthog.key")
val posthogHost = analyticsSetting("wyr.posthog.host")

require(posthogKey.all { it.isLetterOrDigit() || it == '_' || it == '-' }) {
    "wyr.posthog.key must be letters, digits, _ and -"
}
require(posthogHost.none { it == '"' || it == '\\' || it == '$' || it.isWhitespace() }) {
    "wyr.posthog.host is no host: \"$posthogHost\""
}

extra["wyrPosthogKey"] = posthogKey
extra["wyrPosthogHost"] = posthogHost

if (extra.has("wyrAnalyticsPackage")) {
    tasks.register("generateWyrAnalytics") {
        // Read here, into locals, so the task action captures only these and not the script.
        val packageName = project.extra["wyrAnalyticsPackage"] as String
        val appVersion = project.extra["wyrAppVersion"] as String
        val buildNumber = project.extra["wyrBuildNumber"] as Int
        val key = posthogKey
        val host = posthogHost
        val outputDir = layout.buildDirectory.dir("generated/wyrAnalytics/kotlin")
        inputs.property("package", packageName)
        inputs.property("appVersion", appVersion)
        inputs.property("buildNumber", buildNumber)
        inputs.property("key", key)
        inputs.property("host", host)
        outputs.dir(outputDir)

        doLast {
            // Emptied first, so a file written into another package before cannot linger beside it.
            outputDir.get().asFile.deleteRecursively()
            val file = outputDir.get().file("${packageName.replace('.', '/')}/WyrAnalytics.kt").asFile
            file.parentFile.mkdirs()
            file.writeText(
                """
                |package $packageName
                |
                |// Generated by generateWyrAnalytics (gradle/wyr-analytics.gradle.kts) from wyr.posthog.key and
                |// wyr.posthog.host. Do not edit, and never commit: the key is the user's PostHog project's.
                |internal const val POSTHOG_KEY: String = "$key"
                |internal const val POSTHOG_HOST: String = "$host"
                |internal const val APP_VERSION: String = "$appVersion"
                |internal const val BUILD_NUMBER: Int = $buildNumber
                |
                """.trimMargin(),
            )
        }
    }
}
