import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
}

/**
 * The server environment this web build targets (CLAUDE.md §8e), from `-Pwyr.env=dev`: local, dev or
 * prod, local when absent. A page has nothing of its own to read at start, so the name is written into
 * a Kotlin constant, `WYR_ENV`, which the entry point hands to `initKoin`.
 *
 * Checked here as `WyrEnvironment.parse` would, so a name it does not know fails the build rather than
 * every page load.
 */
val generateWyrEnv by tasks.registering {
    val requested = providers.gradleProperty("wyr.env").orElse("")
    val outputDir = layout.buildDirectory.dir("generated/wyrEnv/kotlin")
    inputs.property("environment", requested)
    outputs.dir(outputDir)

    doLast {
        val name =
            requested
                .get()
                .trim()
                .lowercase()
                .ifEmpty { "local" }
        require(name in setOf("local", "dev", "prod")) {
            "wyr.env must be local, dev or prod, but is \"${requested.get()}\""
        }
        val file = outputDir.get().file("io/ntole/wyr/WyrEnv.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package io.ntole.wyr
            |
            |// Generated by :app:webApp's generateWyrEnv from -Pwyr.env. Do not edit.
            |internal const val WYR_ENV: String = "$name"
            |
            """.trimMargin(),
        )
    }
}

kotlin {
    js {
        browser()
        binaries.executable()
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        binaries.executable()
    }

    sourceSets {
        commonMain.dependencies {
            implementation(project(":app:shared"))

            implementation(libs.compose.ui)
        }
        webMain.configure {
            kotlin.srcDir(generateWyrEnv)
        }
    }
}
